version: '3.8'

services:
  java-app:
    image: 178.128.161.182:8086/java1.0:latest  # Use the image you created earlier
    ports:
      - "8080:8080"  # Expose port 8080 (or whichever port your app uses)
    environment:
      - DB_HOST=mysql  # Point to the MySQL container (the service name)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

  mysql:
    image: mysql:5.7  # Use the official MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Root password for MySQL
      - MYSQL_DATABASE=${MYSQL_DATABASE}  # Database to create
      - MYSQL_USER=${MYSQL_USER}  # Custom user for MySQL
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # Custom user password
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
