version: '3.8'

services:
  java-app:
    build: .              # builds image from your Dockerfile
    ports:
      - "8080:8080"       # makes app available on localhost:8080
    environment:
      - DB_HOST=mysql     # tells app where the DB is (service name = mysql)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

  mysql:
    image: mysql:5.7      # official MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql  # saves DB data so it doesn’t disappear
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
